/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PcAmbulanceWlList {
    }
}
declare global {
    interface HTMLPcAmbulanceWlListElement extends Components.PcAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLPcAmbulanceWlListElement: {
        prototype: HTMLPcAmbulanceWlListElement;
        new (): HTMLPcAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "pc-ambulance-wl-list": HTMLPcAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface PcAmbulanceWlList {
    }
    interface IntrinsicElements {
        "pc-ambulance-wl-list": PcAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pc-ambulance-wl-list": LocalJSX.PcAmbulanceWlList & JSXBase.HTMLAttributes<HTMLPcAmbulanceWlListElement>;
        }
    }
}
